### ISSUE TITLE
There are no pictures about this mod in th eproject page

### ISSUE THREAD

**Issue by OGArist0tle** [p455w0rd/StoneCraftingTable#1]
this is an issue

bruh

**Comment by p455w0rd** [comment]
wot is eproject? that some equivalent exchange rip off?

bruh

**Comment by p455w0rd** [comment]
I didn't want to make any brash decision on this issue. So I took a few days to ponder whether or not this was a good idea. After a small amount of time, I have added a gif to the project page. It also has JEI integration now :) https://minecraft.curseforge.com/projects/stone-crafting-table
